# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Github Package

on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - 'pom.xml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 17
          java-package: jdk
          architecture: x64
          cache: maven
      - name: Build dough
        if: github.event_name != 'pull_request'
        run: mvn -B package --file pom.xml --errors
      - name: Publish dough
        if: github.event_name != 'pull_request'
        run: mvn -B deploy --file pom-github-package.xml --errors
        env:
          GITHUB_TOKEN: ${{ github.token }}